---
name: Config-PackageGlobal-OO
version: 0.02
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
abstract: A generic configuration object for modules with package global configuration
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Context::Handle: 0.01
  Test::Exception: 0
  ok: 0
provides:
  Config::PackageGlobal::OO:
    file: lib/Config/PackageGlobal/OO.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
